server {
    listen       80;
    server_name  localhost;

    # 允许请求头中包含下划线（默认off，会丢弃 xxl_sso_token 等带下划线的header）
    #underscores_in_headers on;

    # 前端静态资源
    root  /usr/share/nginx/html;
    index index.html;

    # 开启 gzip 预压缩文件（构建产物已生成 .gz）
    gzip_static on;

    # 单页应用路由支持（前端 History 模式）
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 后端API反向代理（docker-compose 内部服务名）
    location /api/ {
        proxy_pass   http://xxl-boot-api:8081/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
